[build]
builder = "nixpacks"
buildCommand = "cd backend && npm install && npx prisma generate"

[deploy]
startCommand = "cd backend && npx prisma db push && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
